{
 "title": "ffmpeg",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Framerate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "FPS" } },
   "targets": [
    {
     "expr": "irate(ffmpeg_progress_frame_total[1m])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ffmpeg_progress_bytes_total[1m]) * 8",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Quantizer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "q" } },
   "targets": [
    {
     "expr": "ffmpeg_progress_quantizer",
     "legendFormat": "{{id}}: Output {{output}}, Stream {{stream}}"
    }
   ]
  },
  {
   "title": "Dropped Frames",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "irate(ffmpeg_progress_dropped_total[1m])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Duplicate Frames",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "irate(ffmpeg_progress_duplicate_total[1m])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Current Timestamp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "ffmpeg_progress_us_total", "legendFormat": "{{ id }}" }
   ]
  }
 ]
}